# Generated by Django 5.2.4 on 2025-09-24 17:13

import boleta_api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('monto_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_sobrante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de Operación')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Recibida', 'Recibida')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RazonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'boleta_api_razonsocial',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, choices=[('Gerencia General', 'Gerencia General'), ('Industria', 'Industria'), ('Minería', 'Minería'), ('Mantenimiento', 'Mantenimiento'), ('Petroquímica', 'Petroquímica'), ('Administración', 'Administración'), ('Contabilidad', 'Contabilidad'), ('Tecnología de la Información', 'Tecnología de la Información'), ('Logística - Almacén', 'Logística - Almacén'), ('Recursos Humanos', 'Recursos Humanos'), ('Comercial', 'Comercial'), ('SIG. HSEQ', 'SIG. HSEQ'), ('Seguridad de Maquinaria', 'Seguridad de Maquinaria'), ('Comité CSSO', 'Comité CSSO')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', boleta_api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Aprobación', 'Aprobación'), ('Eliminación', 'Eliminación'), ('Actualización', 'Actualización')], max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(db_index=True, default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='arqueos/')),
                ('tipo', models.CharField(choices=[('comprobante', 'Comprobante'), ('foto', 'Foto'), ('otro', 'Otro')], default='comprobante', max_length=20)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='boleta_api.arqueocaja')),
            ],
        ),
        migrations.CreateModel(
            name='CorreccionOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_original', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_correccion', models.CharField(max_length=255)),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='boleta_api.documentogasto')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], db_index=True, default='Cerrada', max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boleta_api.guiasalida')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalArqueoCaja',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_operacion', models.CharField(db_index=True, max_length=50)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical arqueo caja',
                'verbose_name_plural': 'historical arqueo cajas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('total_soles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentogasto',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='boleta_api.liquidacion'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('secuencia', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('tipo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(db_index=True, default=django.utils.timezone.now)),
                ('area', models.CharField(max_length=100)),
                ('tipo_solicitud', models.CharField(choices=[('Viáticos', 'Viáticos'), ('Movilidad', 'Movilidad'), ('Compras', 'Compras'), ('Otros Gastos', 'Otros Gastos')], default='Compras', max_length=50)),
                ('concepto_gasto', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=80)),
                ('observacion', models.TextField(blank=True)),
                ('total_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_transferencia', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_liquidacion', models.DateField(blank=True, db_index=True, null=True)),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Gasto',
                'verbose_name_plural': 'Solicitudes de Gasto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='boleta_api.solicitud'),
        ),
        migrations.CreateModel(
            name='HistoricalLiquidacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('total_soles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='boleta_api.solicitud')),
            ],
            options={
                'verbose_name': 'historical liquidacion',
                'verbose_name_plural': 'historical liquidacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='documentogasto',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='boleta_api.solicitud'),
        ),
        migrations.CreateModel(
            name='SolicitudArqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='N° Operación')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('monto_arqueo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Arqueo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('incluida_en_arqueo', 'Incluida en Arqueo'), ('liquidada', 'Liquidada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arqueo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Arqueo',
                'verbose_name_plural': 'Solicitudes de Arqueo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('entradas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('solicitud', 'Solicitud')], default='manual', max_length=10)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='boleta_api.arqueocaja')),
                ('solicitud_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boleta_api.solicitudarqueo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudGastoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], max_length=80)),
                ('estado_nuevo', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], max_length=80)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='boleta_api.solicitud')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['fecha'], name='boleta_api__fecha_979462_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['usuario'], name='boleta_api__usuario_99ae25_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['estado'], name='boleta_api__estado_7ed24b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudarqueo',
            index=models.Index(fields=['numero_operacion'], name='boleta_api__numero__2fad2e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudarqueo',
            index=models.Index(fields=['estado'], name='boleta_api__estado_74041e_idx'),
        ),
    ]
