# Generated by Django 5.2.4 on 2025-09-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalliquidacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de Envío'), ('PENDIENTE_ATENCION', 'Pendiente para Atención'), ('ATENDIDO_PEND_LIQ', 'Atendido, Pendiente de Liquidación'), ('ENV_APROBACION', 'Liquidación enviada para Aprobación'), ('APROBADA', 'Liquidación Aprobada'), ('RECHAZADA', 'Rechazado')], db_index=True, default='PENDIENTE_ENVIO', max_length=30),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de Envío'), ('PENDIENTE_ATENCION', 'Pendiente para Atención'), ('ATENDIDO_PEND_LIQ', 'Atendido, Pendiente de Liquidación'), ('ENV_APROBACION', 'Liquidación enviada para Aprobación'), ('APROBADA', 'Liquidación Aprobada'), ('RECHAZADA', 'Rechazado')], db_index=True, default='PENDIENTE_ENVIO', max_length=30),
        ),
    ]
