# Generated by Django 5.2.4 on 2025-09-24 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='estado',
            field=models.CharField(default='inicial', max_length=50),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='razonsocial',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
