# Generated by Django 5.2.4 on 2025-09-24 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0002_razonsocial_estado_razonsocial_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razonsocial',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
