# Generated by Django 5.2.4 on 2025-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0002_alter_historicalliquidacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalliquidacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100),
        ),
    ]
