# Generated by Django 5.2.4 on 2025-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0003_alter_historicalliquidacion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentogasto',
            name='concepto_gasto',
        ),
    ]
