# Generated by Django 5.2.4 on 2025-09-22 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta_api', '0004_remove_documentogasto_concepto_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='hora',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
